### ISSUE TITLE
test run from this repo consistently fail to cleanup service accoutns 

### ISSUE THREAD

**Issue by codyoss** [googleapis/env-tests-logging#81]
Twice in the last week I have manually deleted around 50 SA's that tests in this repo create. There seems to be a bug somewhere in this framework. Hopefully there are logs that show this too.

Particularly I am noticing this in our Go repo: https://github.com/googleapis/env-tests-logging/blob/b44573e60cb3129c8776e7418bbe92f8e5046ea4/envctl/env_scripts/go/cloudrun.sh#L22

**Comment by daniel-sanche** [comment]
This was due to a silent issue in the destroy script, which meant that resources weren't cleaned up in the go tests as expected. This should have been fixed back in https://github.com/googleapis/google-cloud-go/pull/6384.

I just checked the project to make sure, and I'm not seeing any stray service accounts any more
